// <auto-generated />
using System;
using Lanre.Module.Poll.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lanre.Module.Poll.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PollContext))]
    partial class PollContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Lanre.Module.Poll.Domain.VoteList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VoteList", "Poll");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bddba00-f200-402d-b45b-6f1634a5f622"),
                            Name = "May 2022 Poll",
                            UserId = "0000000000"
                        },
                        new
                        {
                            Id = new Guid("332fb5ab-2eab-4393-a920-9b46faed3cb5"),
                            Name = "June 2022 Poll",
                            UserId = "0000000000"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
